-- ForgeShield OT — Postgres initialization.
-- Runs once on first container start (empty data dir).
-- UUID primary keys are generated by the application (Python uuid4), so no
-- UUID extension is strictly required, but pgcrypto is handy for gen_random_uuid().
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Optional: semantic retrieval for the AI layer. Disabled by default
-- (AI_VECTOR_ENABLED=false). Requires the pgvector image; ignored otherwise.
-- CREATE EXTENSION IF NOT EXISTS vector;
