"""initial schema

Revision ID: 3d6a9e9ba513
Revises: 
Create Date: 2026-06-28 07:57:34.380830
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '3d6a9e9ba513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('supabase_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OT_SECURITY_ENGINEER', 'SOC_ANALYST', 'COMPLIANCE_OFFICER', 'VIEWER', name='rolename'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_index(op.f('ix_app_user_supabase_id'), 'app_user', ['supabase_id'], unique=True)
    op.create_table('compliance_framework',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.Enum('IEC_62443', 'NERC_CIP', 'TSA', 'NIS2', 'NCA_OTCC', 'CISA_CPG', 'ISO_27001', 'NIST_800_82', 'MITRE_ATTCK_ICS', name='frameworkkey'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_framework_id'), 'compliance_framework', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_framework_is_demo'), 'compliance_framework', ['is_demo'], unique=False)
    op.create_index(op.f('ix_compliance_framework_key'), 'compliance_framework', ['key'], unique=True)
    op.create_table('integration',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('SIEM_WEBHOOK', 'SPLUNK', 'SENTINEL', 'SERVICENOW', 'JIRA', 'DEFENDER', 'OT_PLATFORM_IMPORT', 'VULN_SCANNER_IMPORT', 'OEM_IMPORT', name='integrationkind'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direction', sa.Enum('EXPORT', 'IMPORT', name='integrationdirection'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_sync_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_id'), 'integration', ['id'], unique=False)
    op.create_index(op.f('ix_integration_is_demo'), 'integration', ['is_demo'], unique=False)
    op.create_index(op.f('ix_integration_kind'), 'integration', ['kind'], unique=False)
    op.create_table('role',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'OT_SECURITY_ENGINEER', 'SOC_ANALYST', 'COMPLIANCE_OFFICER', 'VIEWER', name='rolename'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('site',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_code'), 'site', ['code'], unique=False)
    op.create_index(op.f('ix_site_id'), 'site', ['id'], unique=False)
    op.create_index(op.f('ix_site_is_demo'), 'site', ['is_demo'], unique=False)
    op.create_index(op.f('ix_site_name'), 'site', ['name'], unique=False)
    op.create_table('vulnerability',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cve_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cvss_base', sa.Float(), nullable=False),
    sa.Column('cvss_vector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('epss', sa.Float(), nullable=True),
    sa.Column('known_exploited', sa.Boolean(), nullable=False),
    sa.Column('advisory_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('affected_versions', sa.JSON(), nullable=True),
    sa.Column('remediation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workaround', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('patch_available', sa.Boolean(), nullable=False),
    sa.Column('patch_risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'REQUIRES_OUTAGE', name='patchrisk'), nullable=False),
    sa.Column('required_downtime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ot_compensating_controls', sa.JSON(), nullable=True),
    sa.Column('safety_impact', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='impactlevel'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_kev_cvss', 'vulnerability', ['known_exploited', 'cvss_base'], unique=False)
    op.create_index(op.f('ix_vulnerability_cve_id'), 'vulnerability', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vulnerability_id'), 'vulnerability', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerability_is_demo'), 'vulnerability', ['is_demo'], unique=False)
    op.create_index(op.f('ix_vulnerability_known_exploited'), 'vulnerability', ['known_exploited'], unique=False)
    op.create_index(op.f('ix_vulnerability_product'), 'vulnerability', ['product'], unique=False)
    op.create_index(op.f('ix_vulnerability_vendor'), 'vulnerability', ['vendor'], unique=False)
    op.create_table('ai_conversation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('use_case', sa.Enum('CHAT', 'ASSET_RISK', 'DAILY_BRIEF', 'VULN_IMPACT', 'REMEDIATION_PLAN', 'COMPLIANCE_GAP', 'CONFIG_CHANGE', 'INCIDENT_SUMMARY', 'EXEC_SUMMARY', 'ALERT_TRANSLATE', 'NEXT_ACTION', 'EVIDENCE_MAP', name='aiusecase'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_id'), 'ai_conversation', ['id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_user_id'), 'ai_conversation', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'USER_PROVISION', 'ASSET_CREATE', 'ASSET_UPDATE', 'ASSET_DELETE', 'ASSET_IMPORT', 'ASSET_EXPORT', 'CONFIG_BASELINE', 'CONFIG_SNAPSHOT', 'CHANGE_DISPOSITION', 'DETECTION_STATUS_CHANGE', 'VULN_RISK_ACCEPTANCE', 'VULN_STATUS_CHANGE', 'COMPLIANCE_EVIDENCE_UPLOAD', 'CONTROL_STATUS_CHANGE', 'INCIDENT_CREATE', 'INCIDENT_UPDATE', 'AI_PROMPT', 'AI_RESPONSE', 'REPORT_GENERATE', 'INTEGRATION_EXPORT', 'INTEGRATION_IMPORT', 'INGEST', 'RISK_RECOMPUTE', name='auditaction'), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('compliance_control',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('framework_id', sa.Uuid(), nullable=False),
    sa.Column('control_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evidence_required', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PARTIAL', 'IMPLEMENTED', 'NOT_APPLICABLE', name='controlstatus'), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('ai_gap_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_framework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_control_control_ref'), 'compliance_control', ['control_ref'], unique=False)
    op.create_index(op.f('ix_compliance_control_framework_id'), 'compliance_control', ['framework_id'], unique=False)
    op.create_index(op.f('ix_compliance_control_id'), 'compliance_control', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_control_is_demo'), 'compliance_control', ['is_demo'], unique=False)
    op.create_index(op.f('ix_compliance_control_status'), 'compliance_control', ['status'], unique=False)
    op.create_index('ix_control_framework_status', 'compliance_control', ['framework_id', 'status'], unique=False)
    op.create_table('incident',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CONTAINED', 'RESOLVED', 'CLOSED', name='incidentstatus'), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attck_ics_technique', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lead_owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('containment_actions', sa.JSON(), nullable=True),
    sa.Column('recovery_actions', sa.JSON(), nullable=True),
    sa.Column('lessons_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compliance_impact', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executive_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_id'), 'incident', ['id'], unique=False)
    op.create_index(op.f('ix_incident_is_demo'), 'incident', ['is_demo'], unique=False)
    op.create_index(op.f('ix_incident_reference'), 'incident', ['reference'], unique=True)
    op.create_index(op.f('ix_incident_severity'), 'incident', ['severity'], unique=False)
    op.create_index(op.f('ix_incident_site_id'), 'incident', ['site_id'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_index('ix_incident_status_sev', 'incident', ['status', 'severity'], unique=False)
    op.create_table('report',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('EXEC_RISK_SUMMARY', 'ASSET_INVENTORY', 'VULN_REMEDIATION_PLAN', 'UNAUTHORIZED_CHANGE', 'COMPLIANCE_GAP', 'IEC62443_EVIDENCE', 'NERC_CIP_EVIDENCE', 'NIS2_READINESS', 'OTCC_READINESS', 'INCIDENT_REPORT', 'AI_DAILY_BRIEF', name='reporttype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fmt', sa.Enum('MARKDOWN', 'HTML', 'PDF', name='reportformat'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_is_demo'), 'report', ['is_demo'], unique=False)
    op.create_index(op.f('ix_report_report_type'), 'report', ['report_type'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('zone',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purdue_level', sa.Enum('L0', 'L1', 'L2', 'L3', 'L4', 'L5', name='purduelevel'), nullable=False),
    sa.Column('conduit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('internet_exposed', sa.Boolean(), nullable=False),
    sa.Column('it_reachable', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_id'), 'zone', ['id'], unique=False)
    op.create_index(op.f('ix_zone_internet_exposed'), 'zone', ['internet_exposed'], unique=False)
    op.create_index(op.f('ix_zone_is_demo'), 'zone', ['is_demo'], unique=False)
    op.create_index(op.f('ix_zone_name'), 'zone', ['name'], unique=False)
    op.create_index(op.f('ix_zone_purdue_level'), 'zone', ['purdue_level'], unique=False)
    op.create_index(op.f('ix_zone_site_id'), 'zone', ['site_id'], unique=False)
    op.create_table('ai_message',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=True),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('safe_ot_actions', sa.JSON(), nullable=True),
    sa.Column('provider_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('use_case', sa.Enum('CHAT', 'ASSET_RISK', 'DAILY_BRIEF', 'VULN_IMPACT', 'REMEDIATION_PLAN', 'COMPLIANCE_GAP', 'CONFIG_CHANGE', 'INCIDENT_SUMMARY', 'EXEC_SUMMARY', 'ALERT_TRANSLATE', 'NEXT_ACTION', 'EVIDENCE_MAP', name='aiusecase'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_message_conversation_id'), 'ai_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_message_id'), 'ai_message', ['id'], unique=False)
    op.create_table('asset',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('firmware_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('software_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('process_line', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purdue_level', sa.Enum('L0', 'L1', 'L2', 'L3', 'L4', 'L5', name='purduelevel'), nullable=False),
    sa.Column('conduit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_type', sa.Enum('PLC', 'RTU', 'HMI', 'SCADA_SERVER', 'HISTORIAN', 'ENG_WORKSTATION', 'SAFETY_SIS', 'NETWORK_DEVICE', 'REMOTE_ACCESS_GATEWAY', 'IIOT_EDGE', 'OEM_VENDOR_SYSTEM', name='assettype'), nullable=False),
    sa.Column('criticality', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'SAFETY_CRITICAL', name='criticality'), nullable=False),
    sa.Column('safety_impact', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='impactlevel'), nullable=False),
    sa.Column('business_impact', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='impactlevel'), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('discovery_source', sa.Enum('PASSIVE_NETWORK', 'MANUAL', 'CSV_IMPORT', 'EDR', 'FIREWALL', 'OEM_IMPORT', 'SEED', name='discoverysource'), nullable=False),
    sa.Column('support_status', sa.Enum('SUPPORTED', 'EXTENDED', 'UNSUPPORTED', 'UNKNOWN', name='supportstatus'), nullable=False),
    sa.Column('patch_status', sa.Enum('CURRENT', 'OUTDATED', 'EOL', 'UNKNOWN', name='patchstatus'), nullable=False),
    sa.Column('os_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('backup_available', sa.Boolean(), nullable=False),
    sa.Column('config_available', sa.Boolean(), nullable=False),
    sa.Column('internet_reachable', sa.Boolean(), nullable=False),
    sa.Column('it_reachable', sa.Boolean(), nullable=False),
    sa.Column('remote_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('endpoint_protection_installed', sa.Boolean(), nullable=False),
    sa.Column('endpoint_protection_healthy', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_band', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='riskband'), nullable=False),
    sa.Column('compliance_tags', sa.JSON(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_asset_tag'), 'asset', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_asset_asset_type'), 'asset', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_criticality'), 'asset', ['criticality'], unique=False)
    op.create_index(op.f('ix_asset_hostname'), 'asset', ['hostname'], unique=False)
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_index(op.f('ix_asset_ip_address'), 'asset', ['ip_address'], unique=False)
    op.create_index(op.f('ix_asset_is_demo'), 'asset', ['is_demo'], unique=False)
    op.create_index(op.f('ix_asset_last_seen'), 'asset', ['last_seen'], unique=False)
    op.create_index(op.f('ix_asset_mac_address'), 'asset', ['mac_address'], unique=False)
    op.create_index(op.f('ix_asset_model'), 'asset', ['model'], unique=False)
    op.create_index(op.f('ix_asset_purdue_level'), 'asset', ['purdue_level'], unique=False)
    op.create_index('ix_asset_risk', 'asset', ['risk_band', 'risk_score'], unique=False)
    op.create_index(op.f('ix_asset_risk_band'), 'asset', ['risk_band'], unique=False)
    op.create_index(op.f('ix_asset_risk_score'), 'asset', ['risk_score'], unique=False)
    op.create_index(op.f('ix_asset_site_id'), 'asset', ['site_id'], unique=False)
    op.create_index('ix_asset_site_type', 'asset', ['site_id', 'asset_type'], unique=False)
    op.create_index(op.f('ix_asset_vendor'), 'asset', ['vendor'], unique=False)
    op.create_index(op.f('ix_asset_zone_id'), 'asset', ['zone_id'], unique=False)
    op.create_table('compliance_evidence',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('control_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('ASSET', 'DETECTION', 'CONFIG_CHANGE', 'VULN', 'INCIDENT', 'REPORT', 'MANUAL', name='evidencesourcetype'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auto_linked', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['compliance_control.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_evidence_control_id'), 'compliance_evidence', ['control_id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_id'), 'compliance_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_evidence_is_demo'), 'compliance_evidence', ['is_demo'], unique=False)
    op.create_table('incident_link',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.Enum('DETECTION', 'ASSET', 'VULN', 'CONFIG_CHANGE', name='incidentlinktype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_link_entity_id'), 'incident_link', ['entity_id'], unique=False)
    op.create_index(op.f('ix_incident_link_id'), 'incident_link', ['id'], unique=False)
    op.create_index(op.f('ix_incident_link_incident_id'), 'incident_link', ['incident_id'], unique=False)
    op.create_table('incident_timeline_event',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('NOTE', 'EVIDENCE', 'STATUS_CHANGE', 'CONTAINMENT', 'RECOVERY', 'LINK', name='timelineeventkind'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_event_id'), 'incident_timeline_event', ['id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_event_incident_id'), 'incident_timeline_event', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_timeline_event_is_demo'), 'incident_timeline_event', ['is_demo'], unique=False)
    op.create_index('ix_timeline_incident_time', 'incident_timeline_event', ['incident_id', 'occurred_at'], unique=False)
    op.create_table('asset_relationship',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('src_asset_id', sa.Uuid(), nullable=False),
    sa.Column('dst_asset_id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.Enum('MODBUS_TCP', 'S7COMM', 'ETHERNET_IP_CIP', 'OPC_UA', 'DNP3', 'PROFINET', 'BACNET', 'IEC_60870_5_104', 'MQTT', 'HTTP', 'HTTPS', 'SMB', 'RDP', 'SSH', name='normalizedprotocol'), nullable=True),
    sa.Column('relationship_type', sa.Enum('COMM', 'EW_TO_PLC', 'REMOTE_ACCESS', 'MANAGEMENT', name='relationshiptype'), nullable=False),
    sa.Column('is_unknown', sa.Boolean(), nullable=False),
    sa.Column('is_internet_path', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dst_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['src_asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_relationship_dst_asset_id'), 'asset_relationship', ['dst_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationship_id'), 'asset_relationship', ['id'], unique=False)
    op.create_index(op.f('ix_asset_relationship_is_demo'), 'asset_relationship', ['is_demo'], unique=False)
    op.create_index(op.f('ix_asset_relationship_src_asset_id'), 'asset_relationship', ['src_asset_id'], unique=False)
    op.create_index('ix_rel_src_dst_proto', 'asset_relationship', ['src_asset_id', 'dst_asset_id', 'protocol'], unique=True)
    op.create_index('ix_rel_unknown', 'asset_relationship', ['is_unknown'], unique=False)
    op.create_table('asset_vulnerability',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('vuln_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PATCH_NOW', 'MITIGATE', 'MONITOR', 'RISK_ACCEPTED', 'REMEDIATED', name='vulnremediationstatus'), nullable=False),
    sa.Column('match_basis', sa.Enum('VENDOR_MODEL_VERSION', 'VENDOR_PRODUCT', 'MANUAL', name='matchbasis'), nullable=False),
    sa.Column('exploitability_in_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_exposure_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('risk_accepted_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_acceptance_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('risk_accepted_until', sa.DateTime(), nullable=True),
    sa.Column('remediation_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['vuln_id'], ['vulnerability.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_vulnerability_asset_id'), 'asset_vulnerability', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_vulnerability_id'), 'asset_vulnerability', ['id'], unique=False)
    op.create_index(op.f('ix_asset_vulnerability_is_demo'), 'asset_vulnerability', ['is_demo'], unique=False)
    op.create_index(op.f('ix_asset_vulnerability_status'), 'asset_vulnerability', ['status'], unique=False)
    op.create_index(op.f('ix_asset_vulnerability_vuln_id'), 'asset_vulnerability', ['vuln_id'], unique=False)
    op.create_index('ix_av_asset_vuln', 'asset_vulnerability', ['asset_id', 'vuln_id'], unique=True)
    op.create_index('ix_av_status', 'asset_vulnerability', ['status'], unique=False)
    op.create_table('config_snapshot',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('PLC_PROGRAM', 'FIRMWARE', 'LOGIC', 'NETWORK_CONFIG', 'FIREWALL_RULES', 'SOFTWARE_INVENTORY', 'ACCOUNT_CONFIG', 'BACKUP_STATUS', name='snapshotkind'), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('PCAP_META', 'NETWORK_OBS', 'SYSLOG', 'EDR', 'FIREWALL', 'MANUAL', 'SEED', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_snapshot_asset_id'), 'config_snapshot', ['asset_id'], unique=False)
    op.create_index(op.f('ix_config_snapshot_id'), 'config_snapshot', ['id'], unique=False)
    op.create_index(op.f('ix_config_snapshot_is_baseline'), 'config_snapshot', ['is_baseline'], unique=False)
    op.create_index(op.f('ix_config_snapshot_is_demo'), 'config_snapshot', ['is_demo'], unique=False)
    op.create_index('ix_snapshot_asset_baseline', 'config_snapshot', ['asset_id', 'is_baseline'], unique=False)
    op.create_table('detection',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detection_type', sa.Enum('MALWARE', 'QUARANTINED_FILE', 'YARA_MATCH', 'HASH_REPUTATION', 'SUSPICIOUS_PROCESS', 'USB_INSERTION', 'AUTORUN_PERSISTENCE', 'UNSIGNED_BINARY', 'ENG_TOOL_ABUSE', 'UNKNOWN_ASSET', 'UNKNOWN_COMM_PATH', 'NEW_DEVICE_IN_ZONE', 'EW_TO_PLC', 'REMOTE_ACCESS', 'RDP_FROM_UNAPPROVED', 'OUT_OF_WINDOW_CHANGE', 'UNUSUAL_OUTBOUND', 'FIREWALL_EXPOSURE', 'UNSUPPORTED_OS', 'KEV_EXPOSURE', 'ENDPOINT_PROTECTION_STATUS', name='detectiontype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidence'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'TRIAGING', 'CONFIRMED', 'FALSE_POSITIVE', 'RESOLVED', name='detectionstatus'), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attck_ics_technique', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attck_ics_tactic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('triage_steps', sa.JSON(), nullable=True),
    sa.Column('safe_containment_steps', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sa.Enum('PCAP_META', 'NETWORK_OBS', 'SYSLOG', 'EDR', 'FIREWALL', 'MANUAL', 'SEED', name='sourcetype'), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detection_asset', 'detection', ['asset_id'], unique=False)
    op.create_index(op.f('ix_detection_asset_id'), 'detection', ['asset_id'], unique=False)
    op.create_index(op.f('ix_detection_detected_at'), 'detection', ['detected_at'], unique=False)
    op.create_index(op.f('ix_detection_detection_type'), 'detection', ['detection_type'], unique=False)
    op.create_index(op.f('ix_detection_id'), 'detection', ['id'], unique=False)
    op.create_index(op.f('ix_detection_is_demo'), 'detection', ['is_demo'], unique=False)
    op.create_index(op.f('ix_detection_severity'), 'detection', ['severity'], unique=False)
    op.create_index(op.f('ix_detection_site_id'), 'detection', ['site_id'], unique=False)
    op.create_index(op.f('ix_detection_status'), 'detection', ['status'], unique=False)
    op.create_index('ix_detection_status_sev', 'detection', ['status', 'severity'], unique=False)
    op.create_table('protocol_observation',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('protocol', sa.Enum('MODBUS_TCP', 'S7COMM', 'ETHERNET_IP_CIP', 'OPC_UA', 'DNP3', 'PROFINET', 'BACNET', 'IEC_60870_5_104', 'MQTT', 'HTTP', 'HTTPS', 'SMB', 'RDP', 'SSH', name='normalizedprotocol'), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'BIDIRECTIONAL', name='protocoldirection'), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('PCAP_META', 'NETWORK_OBS', 'SYSLOG', 'EDR', 'FIREWALL', 'MANUAL', 'SEED', name='sourcetype'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proto_asset', 'protocol_observation', ['asset_id', 'protocol'], unique=True)
    op.create_index(op.f('ix_protocol_observation_asset_id'), 'protocol_observation', ['asset_id'], unique=False)
    op.create_index(op.f('ix_protocol_observation_id'), 'protocol_observation', ['id'], unique=False)
    op.create_index(op.f('ix_protocol_observation_is_demo'), 'protocol_observation', ['is_demo'], unique=False)
    op.create_index(op.f('ix_protocol_observation_protocol'), 'protocol_observation', ['protocol'], unique=False)
    op.create_table('config_change',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('from_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('to_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('disposition', sa.Enum('UNREVIEWED', 'AUTHORIZED', 'UNAUTHORIZED', name='changedisposition'), nullable=False),
    sa.Column('change_ticket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('within_approved_window', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['from_snapshot_id'], ['config_snapshot.id'], ),
    sa.ForeignKeyConstraint(['to_snapshot_id'], ['config_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_change_asset_disp', 'config_change', ['asset_id', 'disposition'], unique=False)
    op.create_index(op.f('ix_config_change_asset_id'), 'config_change', ['asset_id'], unique=False)
    op.create_index(op.f('ix_config_change_disposition'), 'config_change', ['disposition'], unique=False)
    op.create_index(op.f('ix_config_change_id'), 'config_change', ['id'], unique=False)
    op.create_index(op.f('ix_config_change_is_demo'), 'config_change', ['is_demo'], unique=False)
    op.create_table('detection_evidence',
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('detection_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('HASH', 'PROCESS', 'FILE_META', 'YARA', 'USB', 'LOG', 'NETWORK', 'CONFIG', name='evidencekind'), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_evidence_detection_id'), 'detection_evidence', ['detection_id'], unique=False)
    op.create_index(op.f('ix_detection_evidence_id'), 'detection_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_detection_evidence_is_demo'), 'detection_evidence', ['is_demo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_evidence_is_demo'), table_name='detection_evidence')
    op.drop_index(op.f('ix_detection_evidence_id'), table_name='detection_evidence')
    op.drop_index(op.f('ix_detection_evidence_detection_id'), table_name='detection_evidence')
    op.drop_table('detection_evidence')
    op.drop_index(op.f('ix_config_change_is_demo'), table_name='config_change')
    op.drop_index(op.f('ix_config_change_id'), table_name='config_change')
    op.drop_index(op.f('ix_config_change_disposition'), table_name='config_change')
    op.drop_index(op.f('ix_config_change_asset_id'), table_name='config_change')
    op.drop_index('ix_change_asset_disp', table_name='config_change')
    op.drop_table('config_change')
    op.drop_index(op.f('ix_protocol_observation_protocol'), table_name='protocol_observation')
    op.drop_index(op.f('ix_protocol_observation_is_demo'), table_name='protocol_observation')
    op.drop_index(op.f('ix_protocol_observation_id'), table_name='protocol_observation')
    op.drop_index(op.f('ix_protocol_observation_asset_id'), table_name='protocol_observation')
    op.drop_index('ix_proto_asset', table_name='protocol_observation')
    op.drop_table('protocol_observation')
    op.drop_index('ix_detection_status_sev', table_name='detection')
    op.drop_index(op.f('ix_detection_status'), table_name='detection')
    op.drop_index(op.f('ix_detection_site_id'), table_name='detection')
    op.drop_index(op.f('ix_detection_severity'), table_name='detection')
    op.drop_index(op.f('ix_detection_is_demo'), table_name='detection')
    op.drop_index(op.f('ix_detection_id'), table_name='detection')
    op.drop_index(op.f('ix_detection_detection_type'), table_name='detection')
    op.drop_index(op.f('ix_detection_detected_at'), table_name='detection')
    op.drop_index(op.f('ix_detection_asset_id'), table_name='detection')
    op.drop_index('ix_detection_asset', table_name='detection')
    op.drop_table('detection')
    op.drop_index('ix_snapshot_asset_baseline', table_name='config_snapshot')
    op.drop_index(op.f('ix_config_snapshot_is_demo'), table_name='config_snapshot')
    op.drop_index(op.f('ix_config_snapshot_is_baseline'), table_name='config_snapshot')
    op.drop_index(op.f('ix_config_snapshot_id'), table_name='config_snapshot')
    op.drop_index(op.f('ix_config_snapshot_asset_id'), table_name='config_snapshot')
    op.drop_table('config_snapshot')
    op.drop_index('ix_av_status', table_name='asset_vulnerability')
    op.drop_index('ix_av_asset_vuln', table_name='asset_vulnerability')
    op.drop_index(op.f('ix_asset_vulnerability_vuln_id'), table_name='asset_vulnerability')
    op.drop_index(op.f('ix_asset_vulnerability_status'), table_name='asset_vulnerability')
    op.drop_index(op.f('ix_asset_vulnerability_is_demo'), table_name='asset_vulnerability')
    op.drop_index(op.f('ix_asset_vulnerability_id'), table_name='asset_vulnerability')
    op.drop_index(op.f('ix_asset_vulnerability_asset_id'), table_name='asset_vulnerability')
    op.drop_table('asset_vulnerability')
    op.drop_index('ix_rel_unknown', table_name='asset_relationship')
    op.drop_index('ix_rel_src_dst_proto', table_name='asset_relationship')
    op.drop_index(op.f('ix_asset_relationship_src_asset_id'), table_name='asset_relationship')
    op.drop_index(op.f('ix_asset_relationship_is_demo'), table_name='asset_relationship')
    op.drop_index(op.f('ix_asset_relationship_id'), table_name='asset_relationship')
    op.drop_index(op.f('ix_asset_relationship_dst_asset_id'), table_name='asset_relationship')
    op.drop_table('asset_relationship')
    op.drop_index('ix_timeline_incident_time', table_name='incident_timeline_event')
    op.drop_index(op.f('ix_incident_timeline_event_is_demo'), table_name='incident_timeline_event')
    op.drop_index(op.f('ix_incident_timeline_event_incident_id'), table_name='incident_timeline_event')
    op.drop_index(op.f('ix_incident_timeline_event_id'), table_name='incident_timeline_event')
    op.drop_table('incident_timeline_event')
    op.drop_index(op.f('ix_incident_link_incident_id'), table_name='incident_link')
    op.drop_index(op.f('ix_incident_link_id'), table_name='incident_link')
    op.drop_index(op.f('ix_incident_link_entity_id'), table_name='incident_link')
    op.drop_table('incident_link')
    op.drop_index(op.f('ix_compliance_evidence_is_demo'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_id'), table_name='compliance_evidence')
    op.drop_index(op.f('ix_compliance_evidence_control_id'), table_name='compliance_evidence')
    op.drop_table('compliance_evidence')
    op.drop_index(op.f('ix_asset_zone_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_vendor'), table_name='asset')
    op.drop_index('ix_asset_site_type', table_name='asset')
    op.drop_index(op.f('ix_asset_site_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_risk_score'), table_name='asset')
    op.drop_index(op.f('ix_asset_risk_band'), table_name='asset')
    op.drop_index('ix_asset_risk', table_name='asset')
    op.drop_index(op.f('ix_asset_purdue_level'), table_name='asset')
    op.drop_index(op.f('ix_asset_model'), table_name='asset')
    op.drop_index(op.f('ix_asset_mac_address'), table_name='asset')
    op.drop_index(op.f('ix_asset_last_seen'), table_name='asset')
    op.drop_index(op.f('ix_asset_is_demo'), table_name='asset')
    op.drop_index(op.f('ix_asset_ip_address'), table_name='asset')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_hostname'), table_name='asset')
    op.drop_index(op.f('ix_asset_criticality'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_type'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_tag'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_ai_message_id'), table_name='ai_message')
    op.drop_index(op.f('ix_ai_message_conversation_id'), table_name='ai_message')
    op.drop_table('ai_message')
    op.drop_index(op.f('ix_zone_site_id'), table_name='zone')
    op.drop_index(op.f('ix_zone_purdue_level'), table_name='zone')
    op.drop_index(op.f('ix_zone_name'), table_name='zone')
    op.drop_index(op.f('ix_zone_is_demo'), table_name='zone')
    op.drop_index(op.f('ix_zone_internet_exposed'), table_name='zone')
    op.drop_index(op.f('ix_zone_id'), table_name='zone')
    op.drop_table('zone')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_report_report_type'), table_name='report')
    op.drop_index(op.f('ix_report_is_demo'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index('ix_incident_status_sev', table_name='incident')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_site_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_severity'), table_name='incident')
    op.drop_index(op.f('ix_incident_reference'), table_name='incident')
    op.drop_index(op.f('ix_incident_is_demo'), table_name='incident')
    op.drop_index(op.f('ix_incident_id'), table_name='incident')
    op.drop_table('incident')
    op.drop_index('ix_control_framework_status', table_name='compliance_control')
    op.drop_index(op.f('ix_compliance_control_status'), table_name='compliance_control')
    op.drop_index(op.f('ix_compliance_control_is_demo'), table_name='compliance_control')
    op.drop_index(op.f('ix_compliance_control_id'), table_name='compliance_control')
    op.drop_index(op.f('ix_compliance_control_framework_id'), table_name='compliance_control')
    op.drop_index(op.f('ix_compliance_control_control_ref'), table_name='compliance_control')
    op.drop_table('compliance_control')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_action_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_conversation_user_id'), table_name='ai_conversation')
    op.drop_index(op.f('ix_ai_conversation_id'), table_name='ai_conversation')
    op.drop_table('ai_conversation')
    op.drop_index(op.f('ix_vulnerability_vendor'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_product'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_known_exploited'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_is_demo'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_id'), table_name='vulnerability')
    op.drop_index(op.f('ix_vulnerability_cve_id'), table_name='vulnerability')
    op.drop_index('ix_vuln_kev_cvss', table_name='vulnerability')
    op.drop_table('vulnerability')
    op.drop_index(op.f('ix_site_name'), table_name='site')
    op.drop_index(op.f('ix_site_is_demo'), table_name='site')
    op.drop_index(op.f('ix_site_id'), table_name='site')
    op.drop_index(op.f('ix_site_code'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_integration_kind'), table_name='integration')
    op.drop_index(op.f('ix_integration_is_demo'), table_name='integration')
    op.drop_index(op.f('ix_integration_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_index(op.f('ix_compliance_framework_key'), table_name='compliance_framework')
    op.drop_index(op.f('ix_compliance_framework_is_demo'), table_name='compliance_framework')
    op.drop_index(op.f('ix_compliance_framework_id'), table_name='compliance_framework')
    op.drop_table('compliance_framework')
    op.drop_index(op.f('ix_app_user_supabase_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
